# 나이브 베이즈 알고리즘
기계학습분야에서 지도학습(supervised learning) 알고리즘.
분류(Classification)의 목적으로 사용하고, 속성들 사이의 독립을 가정하는 베이즈 정리(Bayes theorem)를 적용한 확률적 분류기법이다.

## 베이즈 정리
두 확률 변수의 **사전확률**과 **사후확률** 사이의 관계를 설명하는 수학적 정리
 - 사전확률 : 어떤 사건에 대해 원인과 결과가 있다고 가정했을 때, 원인이 있을 때 결과가 발생할 확률
 - 사후확률 : 결과가 발생했다는 가정(=조건)에서, 어떤 원인이 발생했을 확률
 - 우도(likelihood) : 원인이 발생했다는 조건에서 결과가 발생했을 확률

## 베이즈 공식
![스크린샷, 2017-11-14 00-31-40](https://i.imgur.com/NjO4rJx.png)
P(A|B) : 사건 B가 일어난 상태에서 사건 A가 일어날 확률

![스크린샷, 2017-11-14 00-56-53](https://i.imgur.com/CSTrjiO.png)
그림과 같이 주사위 2개를 던졌을 때 두 주사위의 차이가 2일 확률이 아니라 주사위를 2개 던졌는데 그중 6이 없는 상태에서 두 주사위의 차이가 2가 될 확률을 구하는 것이다. 따라서 표본공간이 주사위 2개를 던졌을 때 나올 수 있는 모든 결과의 집합에서 주사위 2개를 던졌는데 그중 6이 없는 모든 결과의 집합으로 줄어들었을 때 두 주사위의 차이가 2일 확률을 구하는 것이다.

#### 각 사건의 확률값 보정
![스크린샷, 2017-11-14 00-59-27](https://i.imgur.com/vJXxfXu.png)
줄어든 표본공간의 전체 확률값은 `1`이다. 1이 되어야 하니까 각 값을 `보정`해야 함. 원래 표본공간은 3개이고, 6의 값을 인정하지 않는 조건에 해당하는 집합의 원소가 25개다.

![스크린샷, 2017-11-14 01-00-43](https://i.imgur.com/oi9Mm4t.png)




## 사후 확률 계산 시 발생하는 문제 해결 기법  

**라플라스 스무딩** : 베이즈 정리에 의한 조건부 확률을 계산할 때 학습에 제시되지 않은 요소가 입력에 존재를 하는 경우를 방지하기 위해 확률 값을 보정하는 기법

**Log 변환** : 항상 1보다 작은 값을 갖는 확률의 특성상 입력 벡터를 구성하는 요소가 많아질수록 입력벡터에 대한 각각의 조건부 확률이 너무 작아져서 비교가 불가능한 underflow현상이 발생할 수 있다. 이러한 문제를 해결하기 위해 조건부 확률 계산식에 **로그**를 적용한다.

# 실습

[진행과정]
1. 예제 데이터를 이용하여 빈도/우도 테이블 생성
2. 나이브 베이즈 방정식을 사용하여 각 클래스의 사전확률 계산
3. 입력 벡터에 대한 사후 확률 계산
 
계산되어 나온 사후 확률 중 가장 높은 사후확률을 갖는 클래스
 
학습 벡터 : outlook, temperature, humidity(조건, 특징 벡터를 이루는 구성 요소, 학습벡터, 특징값)
클래스 : playTennis(분류하고자 하는 타깃값, 테니스를 칠 수 있을지 없을지 예측)

## 1. 사후 확률 구하기 
![스크린샷, 2017-11-14 01-12-26](https://i.imgur.com/wUHX6NX.png)
outlook 벡터를 이용해 빈도 테이블을 만든다.

## 2. 사전 확률 구하기
![스크린샷, 2017-11-14 01-13-36](https://i.imgur.com/pIyHTHJ.png)

[클래스 YES에 대한 사전확률] 9/14=0.64
[클래스 NO에 대한 사전확률] 5/14=0.36

## 3. 우도 구하기
결과가 발생한 조건에서 원인이 발생하는 확률(우도) 구하기
[결과값이 Yes일 때, Overcast가 발생할 확률] 4/9=0.44
[결과값이 No일 때, Overcast가 발생할 확률] 발생하지 않음.
[결과값이 No일 때, Outlook벡터의 Rain일 확률] 2/5=0.4
[결과값이 Yes일 때, Outlook벡터의 Rain일 확률] 3/9=0.33
[결과값이 No일 때, Outlook벡터의 Sunny일 확률] 3/5=0.6
[결과값이 Yes일 때, Outlook벡터의 Sunny일 확률] 2/9=0.22


# 파이썬 실습

![스크린샷, 2017-11-15 02-19-29](https://i.imgur.com/JDZzbCj.png)
Outlook 벡터 중에서 Sunny가 발생했을 때, No가 얼마나 발생하는지에 대한 확률
즉, No가 발생할 사전확률과 No가 발생했을 때 Sunny가 발생했을 확률인 우도를 곱한 값을 **Sunny**가 발생할 사전확률로 나눈다.

No가 발생활 사전확률 P(No) = 0.36

### 사후확률
![스크린샷, 2017-11-15 02-21-47](https://i.imgur.com/2YyHwZA.png)
Rain이 발생했을 때, No가 발생할 확률.

**나머지 사후확률값 구해보기!!**


![스크린샷, 2017-11-15 02-23-36](https://i.imgur.com/i1DeaMK.png)
Outlook 벡터와 클래스에 대한 사전확률 및 사후확률과 우도를 구한 과정을 Temperature 벡터와 Humidity 벡터에 각각 적용을 하면
Temperature 벡터와 Humidity 벡터, 클래스에 대한 사전확률, 사후 확률, 우도 등도 함께 마저 구할 수 있게 된다.


## Temperature 데이터 이용
1. 사후확률 구하기
 - Temperature에는 Hot, Mild, Cold이 있고 PlayTennis의 범주는 Yes, NO로 나뉜다.
 - 빈도 테이블을 만들기
 - 우도 테이블 만들기

2. 사전 확률 구하기(Cool)
 - Cool의 사전확률 = Cool의 수 / Temperature 벡터 전체 요소 수(4/14)
 - Hot의 사전확률 = Hot의 수 / Temperature 벡터 전체 요소 수(4/14)
 - Mild이 사전확률 = Mild의 수 / Temperature 벡터 전체 요소 수(2/14)
 - 클래스 No의 사전확률 = 5/14
 - 클래스 Yes의 사전확률 = 9/14
 
3. 우도 구하기
 - 결과가 발생할 조건에서 원인이 발생하는 확률
 - 클래스가 Yes일 때 Tempearture 벡터가 Cool일 확률 = 3/9
 - 클래스가 No일 때 Temperature 벡터가 Cool일 확률 = 1/5
 - 클래스가 Yes일 때 Temperature 벡터가 Hot일 확률 = 2/9
 - 클래스가 No일 때, Temperature 벡터가 Hot일 확률 = 2/5
 - 클래스가 Yes일 때 Temperature 벡터가 Mild일 확률 = 4/9
 - 클래스가 No일 때 Temperature 벡터가 Mild일 확률 = 2/
 
4. Temperature 벡터가 발생했을 때, 클래스가 발생할 사후확률
    ![스크린샷, 2017-11-15 02-33-16](https://i.imgur.com/VrODkfN.png)
 - 즉, No가 발생할 사전 확률가 No가 발생했을 떄 Cool이 발생할 확률인 우도를 곱한 값을 Cool이 발생할 사전확률로 나누어주면 된다.
 - 0.25 = Cool이 발생했을 때, No가 발생할 사후확률값
 

## Humidity 데이터 이용

1. 사후확률 구하기
 - 빈도 테이블 생성 및 우도테이블 생성
 
2. 사전확률 구하기(NO)
     ![스크린샷, 2017-11-15 02-38-21](https://i.imgur.com/odmywRH.png)

3. 우도 구하기
    ![스크린샷, 2017-11-15 02-39-37](https://i.imgur.com/H5yakGW.png)
    
4. Hmidity 벡터가 발생했을 때, 클래스가 발생할 사후 확률
    ![스크린샷, 2017-11-15 02-40-56](https://i.imgur.com/mInoWBr.png)

5. Normal 이라는 벡터가 발생했을 때, No가 발생할 사후 확률
    ![스크린샷, 2017-11-15 02-41-55](https://i.imgur.com/LZLhwqO.png)
    
    
![스크린샷, 2017-11-15 02-44-02](https://i.imgur.com/tKBt4sk.png)


In [25]:
from sklearn.model_selection import train_test_split
    # sklearn.model_selection : scikit-learn 패키지 중 클래스를 나누거나 함수를 통해 train/test를 나눌 때, 모델 검증에 사용되는 서브 패키지
    # train_test_split : 배열 또는 행렬을 임의의 훈련(train) 및 테스트(test) 하위 집합으로 분할하는 모듈
from sklearn.naive_bayes import GaussianNB
    # sklearn.navie_bayes : scikit-learn 패키지 중 나이브 베이즈 기반 모델이 있는 서브 패키지
    # Gaussian : 연속적인 값을 지닌 데이터 처리시, 각 클래스의 연속적인 값들이 가우스 분포(정규분포)를 따른다고 가정하는 나이브 베이즈 모듈중 하나

import pandas as pd # 데이터를 구조화된 형식으로 가공 및 분석할 수 있또록 하는 자료구조를 제공하는 패키지
import numpy as np # Numerical Python의 줄임말로, 고성능 계산, 데이터 분석에 관련된 패키지

tennis_data = pd.read_csv('play_tennis.csv')
tennis_data

Outlook Temperature Humidity    Wind PlayTennis
0      Sunny         Hot     High    Weak         No
1      Sunny         Hot     High  Strong         No
2   Overcast         Hot     High    Weak        Yes
3       Rain        Mild     High    Weak        Yes
4       Rain        Cool   Normal    Weak        Yes
5       Rain        Cool   Normal  Strong         No
6   Overcast        Cool   Normal  Strong        Yes
7      Sunny        Mild     High    Weak         No
8      Sunny        Cool   Normal    Weak        Yes
9       Rain        Mild   Normal    Weak        Yes
10     Sunny        Mild   Normal  Strong        Yes
11  Overcast        Mild     High  Strong        Yes
12  Overcast         Hot   Normal    Weak        Yes
13      Rain        Mild     High  Strong         No

## 문자열 타입에서 숫자 타입으로 변환을 하는 전처리 과정

In [26]:
tennis_data.Outlook = tennis_data.Outlook.replace('Sunny', 0)
tennis_data.Outlook = tennis_data.Outlook.replace('Overcast', 1)
tennis_data.Outlook = tennis_data.Outlook.replace('Rain', 2)

tennis_data.Temperature = tennis_data.Temperature.replace('Hot', 3)
tennis_data.Temperature = tennis_data.Temperature.replace('Mild', 4)
tennis_data.Temperature = tennis_data.Temperature.replace('Cool', 5)

tennis_data.Humidity = tennis_data.Humidity.replace('High', 6)
tennis_data.Humidity = tennis_data.Humidity.replace('Normal', 7)

tennis_data.Wind = tennis_data.Wind.replace('Weak', 8)
tennis_data.Wind = tennis_data.Wind.replace('Strong', 9)

tennis_data.PlayTennis = tennis_data.PlayTennis.replace('No', 10)
tennis_data.PlayTennis = tennis_data.PlayTennis.replace('Yes', 11)

tennis_data


Outlook  Temperature  Humidity  Wind  PlayTennis
0         0            3         6     8          10
1         0            3         6     9          10
2         1            3         6     8          11
3         2            4         6     8          11
4         2            5         7     8          11
5         2            5         7     9          10
6         1            5         7     9          11
7         0            4         6     8          10
8         0            5         7     8          11
9         2            4         7     8          11
10        0            4         7     9          11
11        1            4         6     9          11
12        1            3         7     8          11
13        2            4         6     9          10

In [27]:
# 1. 변수 tennis_data의 칼럼의 값들을 데이터프레임 형태로 추출하고
# np.array를 이용해 추출한 데이터를 배열 형태로 변환한 후 변수 X에 저장

# 2. 변수 tennis_data의 컬럼(PlayTennis)의 값을 데이터프레임 형태로 추출하고
# np.array를 이용해 추출한 데이터를 배열 형태로 변환한 후 변수 y에 저장

X = np.array(pd.DataFrame(tennis_data, columns = ['Outlook', 'Temperature', 'Humidity', 'Wind'])) # 독립변수
y = np.array(pd.DataFrame(tennis_data, columns = ['PlayTennis'])) # target 값 (종속변수)
print(X)
print(y)

[[0 3 6 8]
 [0 3 6 9]
 [1 3 6 8]
 [2 4 6 8]
 [2 5 7 8]
 [2 5 7 9]
 [1 5 7 9]
 [0 4 6 8]
 [0 5 7 8]
 [2 4 7 8]
 [0 4 7 9]
 [1 4 6 9]
 [1 3 7 8]
 [2 4 6 9]]
[[10]
 [10]
 [11]
 [11]
 [11]
 [10]
 [11]
 [10]
 [11]
 [11]
 [11]
 [11]
 [11]
 [10]]


In [28]:
# 14개의 데이터(0~13) 일부를 train 데이터로, 일부를 test 데이터로 한다.
# 일반적으로 train을 7.5, test를 2.5로 둔다.
X_train, X_test, y_train, y_test = train_test_split(X, y)
    # 변수 X : 4개 컬럼에 대한 데이터
    # 변수 y : Playtennis 컬럼의 데이터
    # X_train과 y_train에 75%a
    # X_test과 y_test에 25%가 할당됨

print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))
print(len(X_test)/(len(X_train)+len(X_test)))

10
4
10
4
0.2857142857142857


In [30]:
gnb_clf = GaussianNB()
gnb_clf = gnb_clf.fit(X_train, y_train) # gnb_clf의 함수 fit()에 변수 X_train, y_train을 입력해 가우시안(Gaussian) 나이브 베이즈 모델 생성
gnb_prediction = gnb_clf.predict(X_test) # 입력한 변수 X_test에 대한 클래스 예측 값을 저장
print(gnb_prediction) ## 11: YES, 10 : NO

[10 11 11 10]


/home/chulgyoo/.pyenv/versions/3.6.1/envs/kmooc/lib/python3.6/site-packages/sklearn/utils/validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
